<?php

/**
 * @file
 * Provides events functionality from Cornell Localist.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.as_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The A&S Events module provides various blocks of upcoming events from Localist.') . '</p>';

      return $output;
  }
}
